import { combineEpics } from 'redux-observable';
import {
    loginEpic,
    registerEpic,
    getUserInfoEpic,
    editProfileEpic,
    changePassEpic,
    signUp,
    forgetPassEpic,
    addCreditEpic,
    getReviewEpic,
    postReviewEpic,
    getNotificationsEpic,
    getMainNotificationsEpic,
    buyPackageEpic,
    getAffiliateEpic,
    getNotificationsViewEpic,
    makeSuggestionsEpic,
    buyPracticalWritingEpic,
    loginGoogleEpic,
    loginFacebookEpic,
    loginZaloEpic,
    studyingEpic,
    getConfigEpic,
    changeTargetPointEpic,
    getBlogPostEpic,
    sendOTPEpic,
    confirmOTPEpic,
    postUserDeviceInfoEpic,
    deleteUserDeviceInfoEpic,
    countNewNotificationEpic,
    getWalletEpic,
    searchNotificationEpic,
    readAllNotificationEpic,
    getNotificationsByTypeEpic,
    getOrderHistoryEpic,
    sendReviewEpic,
    saveAddressEpic,
    getAppointmentUpcomingEpic,
    getAppointmentHistoryEpic,
    registerMembershipEpic,
    getMemberOfConversationEpic,
    createConversationEpic,
    getProfileAdminEpic,
    getOrderReplaceableEpic,
    getListPartnerEpic,
    savePartnerEpic,
    deleteConversationEpic,
    searchConversationEpic,
    checkExistConversationEpic,
    checkExistConversationInHomeEpic,
    checkConversationActiveEpic,
    getProfileUserChatEpic,
    sendReviewProductEpic,
    getReviewsOfProductEpic,
    registerAppointmentEpic,
    updateCoordinateForEmployeeEpic,
    deleteNotificationsEpic,
    getStaffsEpic,
    updatePhoneNumberEpic
} from './userEpics';
import { getCountryEpic, getUpdateVersionEpic, getAreaEpic, saveExceptionEpic } from './commonEpic';
import { from } from 'rxjs';
import { getModuleLinkEpic } from './moduleLinkEpic';
import {
    getBranchEpic,
    requestRescueEpic,
    getFeedbackRescueEpic,
    rescueCompleteEpic,
    vehicleTransferEpic,
    getFeedbackTransferEpic,
    transferCompleteEpic,
    searchBranchEpic,
    getTroubleEpic,
    getTroubleForEmployeeEpic,
    getAddressFromPlaceIdEpic,
    getMyLocationByLatLngEpic,
    searchAddressEpic,
    cancelRequestRescueEpic,
    findEmployeeRescueEpic,
    acceptEmployeeRescueEpic,
    updateCoordinateEpic
} from './locationEpic';

import {
    getNewsSellingVehicleEpic,
    postNewsSellingVehicleEpic,
    getNewsSellingVehicleInterestEpic,
    getMyPostSellingVehicleEpic,
    getNewsSellingVehicleInterestDisplayEpic,
    getNewsSellingVehicleInterestHomeEpic,
    updateStatusSoldSellingPostEpic,
    searchCarByVehicleEpic,
    getCategoryCarEpic,
    getSellingVehicleSeenEpic,
    saveSellingVehicleSeenEpic,
    getVehicleDetailEpic,
    updateSellingVehicleEpic,
    deleteSellingVehicleEpic
} from './vehicleEpic';

import {
    getProductCategoryEpic,
    getProductCategoryInHomeEpic,
    getAllProductByCategoryEpic,
    getDetailProductEpic,
    getDetailProductInCartEpic,
    searchProductEpic,
    getCategoryFilterProductEpic,
    getOrdersOfProductEpic,
    orderProductEpic,
    getDetailOrderProductEpic,
    cancelOrderProductEpic,
    saveInfoPaymentEpic,
    getNewProductEpic,
    getHotProductEpic
} from './productEpic';

import {
    getBanksPartnerEpic,
    getFeePaymentPayooEpic,
    createOrderInfoPayooEpic,
    savePaymentPayooDetailEpic
} from './paymentEpic';

import {
    sendFeedback,
} from './feedbackEpic';
import { getPostsEpic } from './postEpic';
import {
    getImageCategoriesEpic,
    getImagesEpic
} from './photoLibraryEpic';

export default combineEpics(
    // counterEpic,
    loginEpic,
    loginGoogleEpic,
    loginFacebookEpic,
    loginZaloEpic,
    registerEpic,
    changePassEpic,
    getUserInfoEpic,
    editProfileEpic,
    getCountryEpic,
    signUp,
    addCreditEpic,
    forgetPassEpic,
    getReviewEpic,
    postReviewEpic,
    getNotificationsEpic,
    getMainNotificationsEpic,
    buyPackageEpic,
    getAffiliateEpic,
    getNotificationsViewEpic,
    makeSuggestionsEpic,
    buyPracticalWritingEpic,
    studyingEpic,
    getConfigEpic,
    changeTargetPointEpic,
    getUpdateVersionEpic,
    // checkPaymentUserEpic,
    getBlogPostEpic,
    //Epic service Demo
    sendOTPEpic,
    confirmOTPEpic,
    postUserDeviceInfoEpic,
    deleteUserDeviceInfoEpic,
    countNewNotificationEpic,
    getWalletEpic,
    registerMembershipEpic,
    getCategoryCarEpic,
    requestRescueEpic,
    getModuleLinkEpic,
    getBranchEpic,
    searchNotificationEpic,
    readAllNotificationEpic,
    getNotificationsByTypeEpic,
    getFeedbackRescueEpic,
    rescueCompleteEpic,
    getOrderHistoryEpic,
    sendReviewEpic,
    saveAddressEpic,
    searchAddressEpic,
    getAreaEpic,
    searchCarByVehicleEpic,
    vehicleTransferEpic,
    getFeedbackTransferEpic,
    transferCompleteEpic,
    getNewsSellingVehicleEpic,
    postNewsSellingVehicleEpic,
    getNewsSellingVehicleInterestEpic,
    getMyPostSellingVehicleEpic,
    updateStatusSoldSellingPostEpic,
    getNewsSellingVehicleInterestDisplayEpic,
    getNewsSellingVehicleInterestHomeEpic,
    getAppointmentUpcomingEpic,
    getAppointmentHistoryEpic,
    getSellingVehicleSeenEpic,
    saveSellingVehicleSeenEpic,
    getVehicleDetailEpic,
    updateSellingVehicleEpic,
    deleteSellingVehicleEpic,
    getMemberOfConversationEpic,
    createConversationEpic,
    getProfileAdminEpic,
    getOrderReplaceableEpic,
    getListPartnerEpic,
    savePartnerEpic,
    deleteConversationEpic,
    searchConversationEpic,
    checkExistConversationEpic,
    checkExistConversationInHomeEpic,
    saveExceptionEpic,
    checkConversationActiveEpic,
    getProfileUserChatEpic,
    getProductCategoryEpic,
    getAllProductByCategoryEpic,
    getDetailProductEpic,
    searchProductEpic,
    sendReviewProductEpic,
    getReviewsOfProductEpic,
    getCategoryFilterProductEpic,
    getOrdersOfProductEpic,
    getDetailProductInCartEpic,
    orderProductEpic,
    getDetailOrderProductEpic,
    cancelOrderProductEpic,
    getProductCategoryInHomeEpic,
    searchBranchEpic,
    registerAppointmentEpic,
    getBanksPartnerEpic,
    getFeePaymentPayooEpic,
    createOrderInfoPayooEpic,
    savePaymentPayooDetailEpic,
    saveInfoPaymentEpic,
    getTroubleEpic,
    getTroubleForEmployeeEpic,
    getNewProductEpic,
    getAddressFromPlaceIdEpic,
    getMyLocationByLatLngEpic,
    getHotProductEpic,
    cancelRequestRescueEpic,
    updateCoordinateEpic,
    findEmployeeRescueEpic,
    acceptEmployeeRescueEpic,
    sendFeedback,
    deleteNotificationsEpic,
    getStaffsEpic,
    getPostsEpic,
    getImageCategoriesEpic,
    getImagesEpic,
    updatePhoneNumberEpic
)   